In [13]:
import pandas as pd
data = pd.read_csv("cooking_fuel.csv")

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1632 entries, 0 to 1631
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transaction_id   1632 non-null   int64
 1   customer_id      1632 non-null   int64
 2   first_name       1632 non-null   object
 3   last_name        1632 non-null   object
 4   email            1632 non-null   object
 5   state            1632 non-null   object
 6   product_type     1632 non-null   object
 7   size             1632 non-null   object
 8   quantity         1632 non-null   int64
 9   unit_price       1632 non-null   float64
 10  discount_amount  1632 non-null   float64
 11  total_amount     1632 non-null   float64
 12  collection_type  1632 non-null   object
 13  sale_date        1632 non-null   object
dtypes: float64(3), int64(3), object(8)
memory usage: 178.6+ KB

In [15]:
data.describe()

,transaction_id,customer_id,quantity,unit_price,discount_amount,total_amount
count,1.632000e+03,1.632000e+03,1632.000000,1632.000000,1632.000000,1632.000000
mean,5.630321e+06,5.719869e+06,2.967525,222.919792,20.394485,646.985735
std,2.576341e+06,2.689383e+06,1.413624,324.616624,74.323349,1096.540588
min,1.009512e+06,1.044891e+06,1.000000,4.490000,0.000000,3.820000
25%,3.437101e+06,3.359075e+06,2.000000,24.990000,0.000000,47.450000
50%,5.668019e+06,6.020319e+06,3.000000,49.950000,0.000000,141.550000
75%,7.801029e+06,8.113787e+06,4.000000,149.000000,1.800000,596.000000
max,9.996681e+06,9.996207e+06,5.000000,849.000000,636.750000,4245.000000

In [16]:
data.head()

,transaction_id,customer_id,first_name,last_name,email,state,product_type,size,quantity,unit_price,discount_amount,total_amount,collection_type,sale_date
0,1800824,7844947,Brianna,Cook,bcook315@yahoo.com,Utah,AmeriGas,100lb,3,149.00,0.0,447.00,Pickup,2024-07-04
1,8921679,9712003,Ahmed,Harris,ahmedharris956@comcast.net,Utah,Blue Rhino,33lb,2,49.95,5.0,94.90,Pickup,2024-11-18
2,2697690,1485654,Patricia,Long,patricia_long@gmail.com.com,Tennessee,AmeriGas,20lb,4,24.99,0.0,99.96,Pickup,2024-07-18
3,7196363,5896624,Felix,Cox,fcox1042@comcast.net,Nevada,AmeriGas,420lb,4,849.00,339.6,3056.40,Delivery,2024-06-07
4,7103303,6170227,David,Patterson,david.patterson@hotmail.com,Louisiana,AmeriGas,100lb,3,149.00,0.0,447.00,Delivery,2024-06-24

In [17]:
data.rename(columns = {"size":"size(lb)"}, inplace = True)

In [18]:
data.head()

,transaction_id,customer_id,first_name,last_name,email,state,product_type,size(lb),quantity,unit_price,discount_amount,total_amount,collection_type,sale_date
0,1800824,7844947,Brianna,Cook,bcook315@yahoo.com,Utah,AmeriGas,100lb,3,149.00,0.0,447.00,Pickup,2024-07-04
1,8921679,9712003,Ahmed,Harris,ahmedharris956@comcast.net,Utah,Blue Rhino,33lb,2,49.95,5.0,94.90,Pickup,2024-11-18
2,2697690,1485654,Patricia,Long,patricia_long@gmail.com.com,Tennessee,AmeriGas,20lb,4,24.99,0.0,99.96,Pickup,2024-07-18
3,7196363,5896624,Felix,Cox,fcox1042@comcast.net,Nevada,AmeriGas,420lb,4,849.00,339.6,3056.40,Delivery,2024-06-07
4,7103303,6170227,David,Patterson,david.patterson@hotmail.com,Louisiana,AmeriGas,100lb,3,149.00,0.0,447.00,Delivery,2024-06-24

In [28]:
data["size(lb)"] = data["size(lb)"].str.replace("lb","",regex = False).astype(float)

AttributeError: Can only use .str accessor with string values!

In [24]:
data.head()

,transaction_id,customer_id,first_name,last_name,email,state,product_type,size(lb),quantity,unit_price,discount_amount,total_amount,collection_type,sale_date
0,1800824,7844947,Brianna,Cook,bcook315@yahoo.com,Utah,AmeriGas,100.0,3,149.00,0.0,447.00,Pickup,2024-07-04
1,8921679,9712003,Ahmed,Harris,ahmedharris956@comcast.net,Utah,Blue Rhino,33.0,2,49.95,5.0,94.90,Pickup,2024-11-18
2,2697690,1485654,Patricia,Long,patricia_long@gmail.com.com,Tennessee,AmeriGas,20.0,4,24.99,0.0,99.96,Pickup,2024-07-18
3,7196363,5896624,Felix,Cox,fcox1042@comcast.net,Nevada,AmeriGas,420.0,4,849.00,339.6,3056.40,Delivery,2024-06-07
4,7103303,6170227,David,Patterson,david.patterson@hotmail.com,Louisiana,AmeriGas,100.0,3,149.00,0.0,447.00,Delivery,2024-06-24

In [29]:
data["sale_date"] = pd.to_datetime(data["sale_date"])

In [34]:
print(data["sale_date"].dtype)

datetime64[ns]

In [35]:
data["name"] = (data["first_name"].fillna("") + " " + data["last_name"].fillna("")).str.strip()

In [36]:
data.head()

,transaction_id,customer_id,first_name,last_name,email,state,product_type,size(lb),quantity,unit_price,discount_amount,total_amount,collection_type,sale_date,name
0,1800824,7844947,Brianna,Cook,bcook315@yahoo.com,Utah,AmeriGas,100.0,3,149.00,0.0,447.00,Pickup,2024-07-04,Brianna Cook
1,8921679,9712003,Ahmed,Harris,ahmedharris956@comcast.net,Utah,Blue Rhino,33.0,2,49.95,5.0,94.90,Pickup,2024-11-18,Ahmed Harris
2,2697690,1485654,Patricia,Long,patricia_long@gmail.com.com,Tennessee,AmeriGas,20.0,4,24.99,0.0,99.96,Pickup,2024-07-18,Patricia Long
3,7196363,5896624,Felix,Cox,fcox1042@comcast.net,Nevada,AmeriGas,420.0,4,849.00,339.6,3056.40,Delivery,2024-06-07,Felix Cox
4,7103303,6170227,David,Patterson,david.patterson@hotmail.com,Louisiana,AmeriGas,100.0,3,149.00,0.0,447.00,Delivery,2024-06-24,David Patterson

In [37]:
data = data.drop(columns = ["first_name","last_name"])

In [38]:
col = data.pop("name")
data.insert(2, "name" , col)

In [39]:
data.head()

,transaction_id,customer_id,name,email,state,product_type,size(lb),quantity,unit_price,discount_amount,total_amount,collection_type,sale_date
0,1800824,7844947,Brianna Cook,bcook315@yahoo.com,Utah,AmeriGas,100.0,3,149.00,0.0,447.00,Pickup,2024-07-04
1,8921679,9712003,Ahmed Harris,ahmedharris956@comcast.net,Utah,Blue Rhino,33.0,2,49.95,5.0,94.90,Pickup,2024-11-18
2,2697690,1485654,Patricia Long,patricia_long@gmail.com.com,Tennessee,AmeriGas,20.0,4,24.99,0.0,99.96,Pickup,2024-07-18
3,7196363,5896624,Felix Cox,fcox1042@comcast.net,Nevada,AmeriGas,420.0,4,849.00,339.6,3056.40,Delivery,2024-06-07
4,7103303,6170227,David Patterson,david.patterson@hotmail.com,Louisiana,AmeriGas,100.0,3,149.00,0.0,447.00,Delivery,2024-06-24

In [42]:
invalid_emails = ~data["email"].str.match(r"^[\w\.-]+@[\w\.-]+\.\w+$", na=False)

invalid_count = invalid_emails.sum()

print(invalid_count)

50

In [43]:
print(data.loc[invalid_emails, "email"])

9                  bcook315@@yahoo.com
30                irina_walker@comcast
67                  ana.wallace@attnet
109            antoine.watson@@att.net
120               thomas.gonzalez@live
145           william.l89@@hotmail.com
165            dmitri.m18sbcglobal.net
177     paulowashington1664@comcastnet
187                elena.collins@yahoo
223                  daniel.t16@attnet
278                  harold38@yahoocom
364          sofia.murray@sbcglobalnet
380               joseph.bailey@icloud
465                      fcook@hotmail
525           dwighthill1035@sbcglobal
600          smendoza1875@sbcglobalnet
639            pooja .coleman@live.com
642                     ana16gmail.com
645             scruz1151@@comcast.net
670            antoine .watson@att.net
719              hana_stevens@@att.net
742           clint_rodriguezyahoo.com
846                   priya.c22@aolcom
875                 pooja74@outlookcom
902                 chantel72yahoo.com
959               william55@@yahoo.com
1032              ana.wallace@@att.net
1137          william.l89@@hotmail.com
1150            erik.martinez@yahoocom
1151              roberto .b18@aol.com
1166                       ana.j42@aol
1175            smendoza1875@sbcglobal
1176                njordan1917aol.com
1214           richard.lewis@icloudcom
1215                  boris51@@att.net
1250         carlosgonzalez1602att.net
1313                  zoeperez1108@aol
1322               fatima.r30gmail.com
1338          robertsnyder1997@hotmail
1345            dburns572@@outlook.com
1393            tamara .b46@icloud.com
1429             zoeperez1108@@aol.com
1431                     egibson@gmail
1456                jason52comcast.net
1523                    ecarteraol.com
1530        stephen.woods@@comcast.net
1542           camille_campbell@aolcom
1608         irina_walker@@comcast.net
1610                  arjun.a20@attnet
1625                    nathan.m61@att
Name: email, dtype: object

In [46]:
invalid_emails.head()

0    False
1    False
2    False
3    False
4    False
Name: email, dtype: bool

In [55]:
good_e = ~data["email"].str.match(r"^[\w\.-]+@[\w\.-]+\.\w+$")

In [56]:
bad_e = data[good_e]

In [57]:
bad_e.head()

,transaction_id,customer_id,name,email,state,product_type,size(lb),quantity,unit_price,discount_amount,total_amount,collection_type,sale_date
9,1467937,7844947,Brianna Cook,bcook315@@yahoo.com,Utah,NGL Energy,420.0,3,849.00,254.7,2292.30,Delivery,2024-05-10
30,9249791,2338687,Irina Walker,irina_walker@comcast,Utah,Suburban Propane,100.0,4,149.00,89.4,506.60,Pickup,2024-06-04
67,7656588,4052834,Ana Wallace,ana.wallace@attnet,Missouri,Ferrellgas,1.0,5,4.49,0.0,22.45,Delivery,2024-06-06
109,8431976,9302946,Antoine Watson,antoine.watson@@att.net,Tennessee,AmeriGas,20.0,4,24.99,0.0,99.96,Pickup,2024-02-11
120,3284720,2893218,Thomas Gonzalez,thomas.gonzalez@live,Florida,Blue Rhino,1.0,4,4.49,0.0,17.96,Pickup,2024-09-05

In [67]:
products = data.groupby("state")["transaction_id"].count()
products = products.sort_values(ascending=False)
print(products)

state
Georgia           86
North Carolina    84
Tennessee         78
Utah              69
Massachusetts     68
Oklahoma          66
New York          64
Ohio              63
Louisiana         62
Florida           62
Michigan          61
Illinois          60
Minnesota         58
New Mexico        57
Nevada            57
Missouri          57
Connecticut       52
Kansas            52
Iowa              48
Maryland          48
Colorado          47
Pennsylvania      44
Wisconsin         43
California        40
Indiana           40
Arizona           38
Texas             37
Oregon            34
Washington        32
Virginia          25
Name: transaction_id, dtype: int64

In [73]:
people = bad_e.groupby("state")["name"].nunique().sort_values(ascending=False)
print(people)

state
Georgia           3
Oregon            3
Tennessee         3
Utah              3
Ohio              3
Maryland          3
Florida           2
California        2
Texas             2
Massachusetts     2
North Carolina    2
Kansas            2
Louisiana         2
Nevada            2
Connecticut       1
Iowa              1
Illinois          1
Missouri          1
Michigan          1
Minnesota         1
New Mexico        1
Oklahoma          1
Washington        1
Wisconsin         1
Name: name, dtype: int64